POST http://localhost:3000/api/login
Accept: application/json
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

###

GET http://localhost:3000/api/login
Accept: application/json
Authorization: Bearer 
Content-Type: application/json